<?php
return[
    'title' => 'ToDoリスト',
    'greeting' => '今日も一日がんばるぞい✨',
    'placeholder_task' => 'タスクを入力',
    'task_list' => 'やること',
    'task_header' => 'やること',
    'start_date' => '開始日',
    'end_date' => '終了日',
    'status' => '状態',
    'edit' => '編集',
    'edit_task_title' => 'タスク編集',
    'update' => '更新',
    'confirm_delete' => '本当に削除しますか？',
    'task_not_found' => 'タスクが見つかりません！',
    'task_not_exist' => 'タスクが存在しません！',
    'back' => '戻る',
    'status_incomplete' => '未完了',
    'status_complete' => '完了',
    'status_done' => '完了済み',
    'reward_section' => 'ご褒美コーナー 🎁',
    'reward_message' => 'お疲れさま！自分にご褒美をあげよう✨',
    'placeholder_reward' => 'ご褒美を入力',
    'placeholder_required_ribbons' => '必要なリボン数',
    'add' => '追加',
    'complete' => '完了',
    'delete' => '削除',
    'ribbons_now' => '現在のリボン',
    'reward_requires' => '🎀 %d個:',
    'great_job' => '🐼偉いぞ！',
];
