<?php
return [
    'title' => 'ToDo List',
    'greeting' => 'Let’s give today our best shot! 🔥',
    'placeholder_task' => 'Add task',
    'task_header' => 'Task',
    'start_date' => 'Start Date',
    'end_date' => 'End Date',
    'status' => 'Status',
    'edit' => 'Edit',
    'edit_task_title' => 'Edit Task',
    'update' => 'Update',
    'confirm_delete' => 'Are you sure you want to delete this task?',
    'task_not_found' => 'Task not found!',
    'task_not_exist' => 'Task does not exist!',
    'back' => 'Back',
    'status_incomplete' => 'Incomplete',
    'status_complete' => 'Complete',
    'status_done' => 'Completed',
    'reward_section' => 'Reward Corner 🎁',
    'reward_message' => 'Great work! Time to treat yourself ✨',
    'placeholder_reward' => 'Enter your reward',
    'placeholder_required_ribbons' => 'Required ribbons',
    'add' => 'Add',
    'task_list' => 'Tasks',
    'complete' => 'Complete',
    'delete' => 'Delete',
    'ribbons_now' => 'Current Ribbons',
    'reward_requires' => '🎀 %d ribbons:',
    'great_job' => '🐼 Well done!',
];