<?php
return [
    'title' => 'ToDolist',
    'greeting' => '今天也一起加油吧 ✨',
    'placeholder_task' => '增加任務',
    'task_list' => '待辦清單',
    'task_header' => '待辦事項',
    'start_date' => '開始日期',
    'end_date' => '結束日期',
    'status' => '狀態',
    'edit' => '編輯',
    'edit_task_title' => '編輯任務',
    'update' => '更新',
    'confirm_delete' => '你確定要刪除這個任務嗎?',
    'task_not_found' => '未找到任務!',
    'task_not_exist' => '此任務不存在!',
    'back' => '返回',
    'status_incomplete' => '未完成',
    'status_complete' => '完成',
    'status_done' => '已完成',
    'reward_section' => '獎勵專區🎁',
    'reward_message' => '給自己一點獎勵吧✨',
    'placeholder_reward' => '輸入獎勵',
    'placeholder_required_ribbons' => '需要的蝴蝶結數',
    'add' => '增加',
    'complete' => '完成',
    'delete' => '刪除',
    'ribbons_now' => '現在的蝴蝶結數',
    'reward_requires' => '🎀 %d個:',
    'great_job' => '🐼 做得好!',

];
